### PR TITLE
add more documentation to groundtest README

### PR DESCRIPTION
**Pull request by mwachs5**
I took the notes from http://www.cl.cam.ac.uk/~mn416/tracegen.html, updated them to what works for me, and added them to this README.

### CODE REVIEW

**Comment by zhemao** [comment]
This looks good, but would you mind rebasing everything into a single commit?

**Comment by mwachs5** [comment]
yes will do that

**Comment by mn416** [comment]
Looks good to me too.  Just a few suggestions about the `tracegen` bit:

  1. Should be `WMO` rather than `WSO`.

  2. In the `Quick reference` section, we could show the new `tracegen+check.sh` script which takes care of executing all the sub-commands.  But I do like that you have kept the sub-commands in the `Longer explanation` section, as that shows what is going on under the hood.

  3. Better not to say that `RISC-V is expected to be WMO`.  How about: `At the time of writing, rocket-chip appears to satisfy WMO`.

Thanks,

Matt

**Comment by mwachs5** [comment]
Thanks for the feedback. I believe I've incorporated your comments, let me know if I should rebase again to a single commit.

**Comment by mn416** [comment]
Thanks for that.

I've gone through the new instructions and noticed a couple of things:

* It's not enough to just do `../scripts/tracegen+check.sh` because that script calls out to a bunch of other scripts in the same directory.  Better to say that `rocket-chip/scripts` must be in your PATH and then drop all occurrences of `../scripts/`.

* I think everything from the `isit` script down can be dropped now that the `tracegen+check.sh` script is there.

While going through this, I applied the changes to a local copy of `README.md`.  Feel free to incorporate these into your PR:

https://github.com/mn416/groundtest/blob/master/README.md

**Comment by mwachs5** [comment]
Thanks for your edits, I merged those into this pull request.

**Comment by zhemao** [comment]
Could you rebase the first three commits (the ones before Matthew's) into a single commit. Once you've done that, I can merge this PR.

**Comment by mwachs5** [comment]
I did rebase the changes, but then realized that this PR is no longer necessary since it matches Matthew's version pulled in earlier. So I can just close this one.

**Comment by mwachs5** [comment]
This is redundant PR since the changes were pulled in already.

**Pull request closed without merging**
